# Generated by Django 5.0.2 on 2024-04-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='последнее обновление'),
        ),
    ]
